// SBI Clerk Pre 2025 Memory Based Paper Based on 20th Sep 2nd Shift (Exact 100 Questions)
module.exports = [
  // English Language: Q1 to Q30
  {
    subject: "English Language (1-30)",
    topic: "Para Jumbles",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (1-5): Rearrange the following sentences (A, B, C, D, E) to form a meaningful paragraph:\n(A) Many merchants are pleased as the steady flow of visitors leads to higher profits.\n(B) However, not everyone shares this excitement because the constant rush creates chaos and congestion.\n(C) Tokyo attracts shoppers from across the globe, making it one of the most vibrant shopping destinations.\n(D) Consequently, Tokyo’s bustling shopping scene presents both promising opportunities and serious challenges.\n(E) Local brands in particular struggle to compete with the dominance of international labels.\n\nWhich of the following is the FIRST sentence after rearrangement?",
    options: ["A", "B", "C", "D", "E"],
    correct: "C",
    explanation: "(C) introduces the general premise: Tokyo attracts shoppers from across the globe."
  },
  {
    subject: "English Language (1-30)",
    topic: "Para Jumbles",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following is the SECOND sentence after rearrangement?",
    options: ["A", "B", "C", "D", "E"],
    correct: "A",
    explanation: "(A) follows logically by noting merchants are pleased with higher profits from visitors."
  },
  {
    subject: "English Language (1-30)",
    topic: "Para Jumbles",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following is the THIRD sentence after rearrangement?",
    options: ["A", "B", "C", "D", "E"],
    correct: "B",
    explanation: "(B) introduces the contrast ('However, not everyone shares this excitement...')."
  },
  {
    subject: "English Language (1-30)",
    topic: "Para Jumbles",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following is the FOURTH sentence after rearrangement?",
    options: ["A", "B", "C", "D", "E"],
    correct: "E",
    explanation: "(E) gives a specific example of the challenges faced by local brands."
  },
  {
    subject: "English Language (1-30)",
    topic: "Para Jumbles",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following is the FIFTH sentence after rearrangement?",
    options: ["A", "B", "C", "D", "E"],
    correct: "D",
    explanation: "(D) provides the concluding summary ('Consequently, Tokyo's bustling shopping scene presents both opportunities and challenges'). Overall sequence: C-A-B-E-D."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (6-14): Read the passage and answer the questions:\n\nIn a small village that often struggled with a shortage of water, the everyday life of the people was filled with challenges. During the summer months, the scarcity of water became severe, and every drop counted. The villagers depended on a common water tank, but many times, the motor pumping the water was left running for too long. As a result, the tank overflowed, wasting not only water but also electricity. It was during such a time of need that the village sarpanch, a lady named Akshara, known for her dedication and hard work, stepped forward to bring a change.\nAkshara had already done much work for the growth and improvement of the village. Under her guidance, the roads had been repaired, small health camps were organized, and farming techniques were upgraded. Yet, she realized that solving the problem of water shortage was the most urgent task. Wasting water when the village was already facing scarcity was something she could not allow to continue.\nDetermined to find a lasting solution, she decided to make use of technology. She discussed the matter with local experts and worked with young villagers who understood simple technical methods. Together, they developed an innovative system to save water. This system involved fitting a sensor in the water tank. The sensor was connected to a simple device that sent a message to mobile phones as soon as the water level reached the top.\nNow, whenever the tank filled with water, a clear message was displayed on the screen of the registered mobile numbers. The person operating the motor would receive the alert immediately and could turn off the motor without delay. This simple step stopped the overflow of water and saved a large quantity from being wasted every day.\nThe results were visible within a few weeks. The villagers noticed a big difference in the amount of water stored and the electricity bills also reduced. The message system became a habit for everyone. People began to check their phones regularly, and even children reminded the elders to turn off the motor when the message arrived, leading to a significant saving of both water and electricity in the village. This example of using technology for a common good quickly drew attention in nearby areas.\nAkshara’s bold move proved that even a simple idea can create a strong impact. By introducing this method, she not only saved water but also inspired the entire village to value and protect their natural resources for the future.\n\nWhich of the following best captures the primary reason Akshara decided to introduce technology in the village?",
    options: ["To reduce the rising electricity bills caused by the motor.", "To inspire children to be more responsible about checking their phones.", "To prevent the continuous overflow of water despite a common water tank.", "To attract the attention of nearby areas by becoming a model village.", "To modernize farming techniques in the village."],
    correct: "C",
    explanation: "The primary problem was the continuous overflow and wastage of water from the common tank."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "According to the passage, which of the following statements is/are FALSE?\n(A) Akshara's initiative directly influenced the villagers' daily habits.\n(B) The village had never faced any other form of development before the water-saving idea.\n(C) Children played a role in ensuring the motor was turned off on time.",
    options: ["Only B", "Both B and C", "Only C", "Both A and B", "All A, B, C"],
    correct: "A",
    explanation: "Statement (B) is false because road repairs, health camps, and farming upgrades had already taken place earlier."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "According to the passage, which factor MOST contributed to the successful implementation of the water-saving system?",
    options: ["Installation of the sensor and alert device", "Previous improvements in farming techniques", "Government incentives for rural technology", "Children reminding elders to check their phones", "Seasonal rainfall improving water supply"],
    correct: "A",
    explanation: "The fitting of the sensor and the connected mobile alert device was the technical foundation of the system."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Why can the villagers' habit of checking their phones be seen as a significant development?",
    options: ["It shows their dependence on mobile entertainment.", "It reflects their growing awareness of resource conservation.", "It indicates their interest in learning new languages.", "It proves the failure of traditional farming techniques.", "It demonstrates their shift to urban lifestyles."],
    correct: "B",
    explanation: "It indicates a collective sense of responsibility and active participation in conserving water and electricity."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following is TRUE according to the passage?\n(A) Children independently managed the motor operations.\n(B) The message system was funded by the state government.\n(C) Akshara’s previous projects included upgrading farming techniques.",
    options: ["Only B", "Both B and C", "Only C", "Both A and B", "All A, B, C"],
    correct: "C",
    explanation: "The passage explicitly notes that under her guidance, farming techniques were upgraded."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "How did the neighbouring areas respond to the success of Akshara’s project?",
    options: ["They approached the village authorities for technical details, hoping to replicate the idea in their own areas.", "They requested government intervention to fund a new network of water tanks across the district.", "They admired the innovation and were motivated to try a similar water-saving method in their own villages.", "They complained that Akshara’s plan increased competition for limited government resources.", "They visited the village only to study the mobile technology but made no plans to implement it themselves."],
    correct: "C",
    explanation: "The example drew widespread attention and motivated surrounding villages to adopt similar water-saving approaches."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Choose the most suitable word to fill the blank in the passage ('...quickly _____________ attention in nearby areas.'):",
    options: ["gone", "rejected", "avoided", "drew", "deflected"],
    correct: "D",
    explanation: "The collocation 'drew attention' means attracted notice or interest."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Which of the following words is same in meaning to 'leading' as used in the passage ('...leading to a significant saving...')?",
    options: ["Resulting", "Misleading", "Inferior", "Following", "Ambiguous"],
    correct: "A",
    explanation: "'Leading to' means causing or resulting in an outcome."
  },
  {
    subject: "English Language (1-30)",
    topic: "Reading Comprehension",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Which of the following words is same in meaning to 'move' as used in the passage ('Akshara’s bold move proved that...')?",
    options: ["Gesture", "Relocation", "Action", "Impulse", "Migration"],
    correct: "C",
    explanation: "'Move' refers to a strategic step, decision, or intentional action."
  },
  {
    subject: "English Language (1-30)",
    topic: "Fill in the Blanks",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "He checked the settings again to prevent another system __________.",
    options: ["break", "update", "crash", "click", "login"],
    correct: "C",
    explanation: "'System crash' is the standard terminology for unexpected computer failure."
  },
  {
    subject: "English Language (1-30)",
    topic: "Fill in the Blanks",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Despite the warning signs, the company continued its risky financial __________.",
    options: ["borrow", "expand", "return", "venture", "balance"],
    correct: "D",
    explanation: "'Financial venture' refers to a business or monetary undertaking involving risk."
  },
  {
    subject: "English Language (1-30)",
    topic: "Fill in the Blanks",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "The committee delayed the vote to allow time for further __________.",
    options: ["assertion", "revision", "mention", "division", "collection"],
    correct: "B",
    explanation: "'Further revision' means modifying, reviewing, or improving a proposal before a vote."
  },
  {
    subject: "English Language (1-30)",
    topic: "Fill in the Blanks",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "The researcher’s findings directly challenged the existing scientific __________.",
    options: ["forums", "context", "framework", "dispute", "featured"],
    correct: "C",
    explanation: "'Scientific framework' refers to an established structure of theories and rules."
  },
  {
    subject: "English Language (1-30)",
    topic: "Fill in the Blanks",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "The software update resolved the bug without affecting system __________.",
    options: ["protocol", "operational", "excess", "integrity", "liable"],
    correct: "D",
    explanation: "'System integrity' denotes the reliability, wholeness, and uncorrupted state of a software system."
  },
  {
    subject: "English Language (1-30)",
    topic: "Error Detection",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Identify the part containing an error:\n\nThe tourists was informed (A)/ that the ferry service (B)/ would resume operation (C)/ after the storm passed. (D)",
    options: ["A", "B", "C", "D", "No error"],
    correct: "A",
    explanation: "Plural subject 'tourists' requires plural auxiliary 'were informed'."
  },
  {
    subject: "English Language (1-30)",
    topic: "Error Detection",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Identify the part containing an error:\n\nHe described the plan (A)/ as both effective (B)/ and was easy to implement (C)/ within the current budget. (D)",
    options: ["A", "B", "C", "D", "No error"],
    correct: "C",
    explanation: "Parallelism with 'both ... and ...': 'both effective (adj) and easy to implement (adj)'. Remove 'was'."
  },
  {
    subject: "English Language (1-30)",
    topic: "Error Detection",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Identify the part containing an error:\n\nShe took the wrong train (A)/ and ended up in (B)/ an unfamiliar station (C)/ she had never been in before. (D)",
    options: ["A", "B", "C", "D", "No error"],
    correct: "D",
    explanation: "When referring to visiting a destination or station, 'been to' is used, not 'been in'."
  },
  {
    subject: "English Language (1-30)",
    topic: "Error Detection",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Identify the part containing an error:\n\nA number of rare birds (A)/ has been spotted (B)/ near the riverbank (C)/ over the past few days. (D)",
    options: ["A", "B", "C", "D", "No error"],
    correct: "B",
    explanation: "'A number of + plural noun' takes a plural verb: 'have been spotted'."
  },
  {
    subject: "English Language (1-30)",
    topic: "Error Detection",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Identify the part containing an error:\n\nThe players practiced hard (A)/ so that they can (B)/ perform well in the (C)/ upcoming regional tournament. (D)",
    options: ["A", "B", "C", "D", "No error"],
    correct: "B",
    explanation: "Tense consistency: past tense main clause 'practiced hard' requires past modal 'could perform' in subordinate clause."
  },
  {
    subject: "English Language (1-30)",
    topic: "Word Rearrangement",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Rearrange the highlighted words:\n\nHimachal Pradesh improve (A) mobile use in government (B) schools to banned (C) focus and well-being.",
    options: ["BAC", "CBA", "BCA", "ACB", "No rearrangement required"],
    correct: "B",
    explanation: "Correct sentence: 'Himachal Pradesh banned (C) mobile use in government (B) schools to improve (A) focus and well-being.' Sequence is CBA."
  },
  {
    subject: "English Language (1-30)",
    topic: "Word Rearrangement",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Rearrange the highlighted words:\n\nKarnataka launched (A) the Deepika Scholarship, higher (B) ₹30,000 yearly to 37,000 schoolgirls in giving (C) education.",
    options: ["CBA", "BCA", "BAC", "ACB", "No rearrangement required"],
    correct: "D",
    explanation: "Correct sentence: 'Karnataka launched (A) the Deepika Scholarship, giving (C) ₹30,000 yearly to 37,000 schoolgirls in higher (B) education.' Sequence is ACB."
  },
  {
    subject: "English Language (1-30)",
    topic: "Word Rearrangement",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Rearrange the highlighted words:\n\nGurgaon’s Ward 22 is composting (A) a zero-waste model with becoming (B), segregation, and community (C) efforts.",
    options: ["CBA", "ACB", "BAC", "BCA", "No rearrangement required"],
    correct: "C",
    explanation: "Correct sentence: 'Gurgaon’s Ward 22 is becoming (B) a zero-waste model with composting (A), segregation, and community (C) efforts.' Sequence is BAC."
  },
  {
    subject: "English Language (1-30)",
    topic: "Word Usage",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Identify the sentence(s) where the word 'CURSE' is used accurately:\n(A) The heavy rain turned out to be a curse for the farmers who were hoping for a dry harvest.\n(B) After stepping on a nail, he let out a loud curse that echoed down the street.\n(C) She gave him a curse of appreciation for helping her with the heavy bags.",
    options: ["Only C", "Both B and C", "Only B", "Both A and B", "All A, B, C"],
    correct: "D",
    explanation: "'Curse' is used properly in (A) (harmful event) and (B) (expletive/swear word). (C) is contradictory."
  },
  {
    subject: "English Language (1-30)",
    topic: "Sentence Improvement",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Improve the bold part: The manager instructed the staff *to took care of all* client requests promptly and efficiently.",
    options: ["to take care of all", "for taking care of all", "to taking care of all", "to takes care of all", "No improvement required"],
    correct: "A",
    explanation: "Infinitive requires base form: 'to take care of all'."
  },
  {
    subject: "English Language (1-30)",
    topic: "Sentence Improvement",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Improve the bold part: The students were excited *for attend the workshop* on artificial intelligence applications.",
    options: ["with attending the workshop", "to attend the workshop", "to attending the workshop", "in attend the workshop", "No improvement required"],
    correct: "B",
    explanation: "Adjective 'excited' is followed by infinitive: 'to attend the workshop'."
  },

  // Quantitative Aptitude: Q31 to Q65
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Directions (31-35): The table shows cheesecakes sold by shops A and B across 3 days:\nSaturday: A = 125, B = 325\nSunday: A = 175, B = 275\nMonday: A = 200, B = 100\n\nCheesecake sold by A on Sunday and Monday is what percentage of total cheesecake sold by B on Saturday and Sunday?",
    options: ["62.5%", "90.5%", "25.50%", "120.25%", "162.5%"],
    correct: "A",
    explanation: "A (Sun + Mon) = 175 + 200 = 375. B (Sat + Sun) = 325 + 275 = 600. Percentage = (375 / 600) × 100 = 62.5%."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Find the ratio of cheesecake sold by B on Saturday to Monday.",
    options: ["10 : 11", "13 : 4", "5 : 4", "4 : 5", "8 : 9"],
    correct: "B",
    explanation: "325 : 100 = 13 : 4."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "The average cheesecake sold by A on Monday and Tuesday is 300. The cheesecake sold by A on Tuesday is what percentage more than cheesecake sold by B on Monday?",
    options: ["100%", "200%", "300%", "400%", "500%"],
    correct: "C",
    explanation: "A (Tue) = 300 × 2 - 200 = 400. B (Mon) = 100. Percentage more = ((400 - 100) / 100) × 100 = 300%."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Find the average cheesecake sold by B on Saturday and A on Sunday.",
    options: ["100", "350", "150", "250", "180"],
    correct: "D",
    explanation: "Average = (325 + 175) / 2 = 500 / 2 = 250."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "If A made 700 cheesecakes (sold + unsold) across all given days, the unsold cheesecake of A is how many less than cheesecakes sold by B on Saturday and Sunday?",
    options: ["400", "480", "150", "360", "380"],
    correct: "A",
    explanation: "Total sold by A = 125 + 175 + 200 = 500. Unsold by A = 700 - 500 = 200. Sold by B (Sat + Sun) = 325 + 275 = 600. Difference = 600 - 200 = 400."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (36-40): The line graph shows total students in schools A, B, C, D in 2018 and 2019:\n2018: A = 120, B = 115, C = 100, D = 120 (Total = 455)\n2019: A = 110, B = 140, C = 135, D = 120 (Total = 505)\n\nFind the ratio of total students in 2018 to 2019.",
    options: ["100 : 101", "91 : 101", "50 : 51", "120 : 121", "80 : 81"],
    correct: "B",
    explanation: "455 : 505 = 91 : 101."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Total students in School B across both years is what percentage more than total students in School A in 2018?",
    options: ["100.5%", "100.25%", "112.5%", "120.25%", "180.125%"],
    correct: "C",
    explanation: "B (both years) = 115 + 140 = 255. A (2018) = 120. Percentage more = ((255 - 120) / 120) × 100 = (135 / 120) × 100 = 112.5%."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "The average number of students in School A in 2018, 2019, and 2020 is 120. Find the total students in A in 2020.",
    options: ["100", "120", "150", "130", "80"],
    correct: "D",
    explanation: "Total in 3 years = 120 × 3 = 360. 2020 = 360 - (120 + 110) = 130."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "In School E, total students in 2019 and 2018 together is 165 more than that of C (both years). The ratio of students in 2019 to 2018 is 3 : 2. Find the difference between students in 2019 and 2018 in E.",
    options: ["100", "90", "50", "120", "80"],
    correct: "E",
    explanation: "C (both years) = 100 + 135 = 235. E total = 235 + 165 = 400. Ratio 3:2 => 5x = 400 => x = 80. Difference = 3x - 2x = 80."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Data Interpretation",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "If the ratio of girls to boys in School D in 2018 is 1 : 3, find the number of boys in School D in 2018.",
    options: ["100", "90", "50", "120", "80"],
    correct: "B",
    explanation: "Total in D (2018) = 120. Boys = (3/4) × 120 = 90."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Mixtures & Allegations",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "A vessel contains 48 liters mixture of milk and water in the ratio 5 : 3. X liters is removed and mixed into another vessel containing 2L milk and 2L water. If the ratio of milk to water in the second vessel becomes 3 : 2, find X.",
    options: ["16", "8", "32", "12", "24"],
    correct: "A",
    explanation: "(2 + 5X/8) / (2 + 3X/8) = 3/2 => 2(16 + 5X) = 3(16 + 3X) => 32 + 10X = 48 + 9X => X = 16 liters."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Mixtures & Allegations",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "In the above mixture problem (with X = 16L), find the difference between the quantity of milk remaining in the first vessel and milk in the second vessel.",
    options: ["10 liters", "18 liters", "15 liters", "12 liters", "8 liters"],
    correct: "B",
    explanation: "Initial milk in 1st = 30L. Milk removed = (5/8) × 16 = 10L. Remaining in 1st = 20L. Milk in 2nd = 2 + 10 = 12L (or 30 - 12 = 18L)."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Percentages & Income",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Sunita spends 65% of monthly salary on rent, grocery, and food in the ratio 3 : 1 : 1. Out of remaining, she invests 50% in mutual funds and saves the rest. If difference between savings and food expenditure is ₹900, find Sunita's salary.",
    options: ["₹10,000", "₹20,000", "₹15,000", "₹12,000", "₹80,000"],
    correct: "B",
    explanation: "Salary = 100x. Total spent = 65x (Rent = 39x, Grocery = 13x, Food = 13x). Remaining = 35x => Savings = 17.5x. 17.5x - 13x = 4.5x = 900 => x = 200. Salary = ₹20,000."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Percentages & Income",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "In Sunita's budget, find the difference between the amount invested in mutual funds and the amount spent on rent.",
    options: ["₹4,100", "₹4,200", "₹4,300", "₹4,400", "₹4,800"],
    correct: "C",
    explanation: "Rent = 39x = ₹7,800. Mutual Fund = 17.5x = ₹3,500. Difference = 7800 - 3500 = ₹4,300."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Partnership",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "A and B started a business with ₹2,000 and ₹6,000 respectively. A invested for 2 months more than B. Total profit was ₹6,600 and A's share was ₹1,800. For how many months did A invest?",
    options: ["16 months", "14 months", "22 months", "18 months", "24 months"],
    correct: "D",
    explanation: "Profit A:B = 1800 : 4800 = 3 : 8. (2000 × (x + 2)) / (6000 × x) = 3/8 => (x + 2) / 3x = 3/8 => 8x + 16 = 9x => x = 16. A's months = 16 + 2 = 18 months."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Time and Work",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "8 men can do a work in 3 days, and (x + 10) women can do it in 4 days. If the ratio of efficiency of a man to a woman is 3 : 1, in how many days can (x + 16) women do the same work?",
    options: ["2 days", "8 days", "6 days", "4 days", "3 days"],
    correct: "E",
    explanation: "Total work = 8 × 3 × 3 = 72 units. 4(x + 10) × 1 = 72 => x + 10 = 18 => x = 8. (x + 16) = 24 women. Time = 72 / (24 × 1) = 3 days."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Boats & Streams",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "The ratio of time taken by a boat downstream to upstream for same distance is 7 : 15 (or 3 : 5). If stream speed is 3 km/hr, find time taken by boat to cover 72 km upstream.",
    options: ["3 hours", "12 hours", "9 hours", "8 hours", "6 hours"],
    correct: "D",
    explanation: "Speed upstream:downstream = 3:5. (x - 3)/(x + 3) = 3/5 => 5x - 15 = 3x + 9 => 2x = 24 => x = 12 km/h. Upstream speed = 12 - 3 = 9 km/h. Time = 72 / 9 = 8 hours."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Mensuration",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "The side of a square equals the breadth of a rectangle. Perimeter of square is 48 cm. If area of rectangle is 216 sq cm, find the length of the rectangle.",
    options: ["20 cm", "15 cm", "16 cm", "18 cm", "24 cm"],
    correct: "D",
    explanation: "Side of square = 48 / 4 = 12 cm = breadth. Length = 216 / 12 = 18 cm."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Problems on Ages",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Ratio of X's age 10 years ago to Y's age 6 years ago is 2 : 3. Ratio of X's age 4 years hence to Y's age 6 years hence will be 5 : 6. Find the difference between present ages of X and Y.",
    options: ["8 years", "6 years", "3 years", "4 years", "2 years"],
    correct: "D",
    explanation: "3x - 30 = 2y - 12 => 3x - 2y = 18. 6x + 24 = 5y + 30 => 6x - 5y = 6. Solving gives x = 26, y = 30. Difference = 30 - 26 = 4 years."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Profit and Loss",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "A shopkeeper marked up an article by 50% above cost price and allowed a discount of ₹360. If the difference between cost price and profit is ₹960, find the marked price.",
    options: ["₹2,800", "₹1,600", "₹1,800", "₹2,000", "₹2,400"],
    correct: "C",
    explanation: "MP = 1.5 CP. SP = 1.5 CP - 360. Profit = 0.5 CP - 360. CP - (0.5 CP - 360) = 0.5 CP + 360 = 960 => 0.5 CP = 600 => CP = 1200. MP = 1.5 × 1200 = ₹1,800."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Ratio and Proportion",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "The ratio of two numbers A and B is 4 : 5. When 40 is added to each, the ratio becomes 5 : 6. If 10 is subtracted from each, find the new ratio of A to B.",
    options: ["15 : 19", "3 : 4", "7 : 9", "9 : 11", "11 : 13"],
    correct: "A",
    explanation: "(4x + 40)/(5x + 40) = 5/6 => 24x + 240 = 25x + 200 => x = 40. A = 160, B = 200. (160 - 10) : (200 - 10) = 150 : 190 = 15 : 19."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simple & Compound Interest",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "A man invested ₹X on SI at 16% p.a. for 5 years and received ₹2,000 interest. If he invests the same amount on CI at 20% p.a. for 2 years, find the amount received.",
    options: ["₹3,000", "₹3,600", "₹3,200", "₹4,000", "₹3,260"],
    correct: "B",
    explanation: "X × 16 × 5 / 100 = 2000 => 0.8X = 2000 => X = ₹2,500. CI Amount = 2500 × (1.20)² = 2500 × 1.44 = ₹3,600."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Averages",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "The average of 4 consecutive odd numbers is 10 and average of 4 consecutive even numbers is 21. Find the sum of the largest odd number and smallest even number.",
    options: ["37", "35", "33", "31", "29"],
    correct: "D",
    explanation: "Odd numbers: 7, 9, 11, 13 (largest = 13). Even numbers: 18, 20, 22, 24 (smallest = 18). Sum = 13 + 18 = 31."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Average Speed",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "A man goes to the gym at 20 km/hr and returns at 30 km/hr. Find the average speed of the entire journey.",
    options: ["24 km/hr", "18 km/hr", "20 km/hr", "16 km/hr", "28 km/hr"],
    correct: "A",
    explanation: "Average speed = (2 × 20 × 30) / (20 + 30) = 1200 / 50 = 24 km/hr."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Mixtures",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "In 128 liters of pure milk, 40 liters of water is mixed and 25% of mixture is taken out. When 'x' liters of water is added, the ratio of milk to water becomes 2 : 1. Find x.",
    options: ["20", "16", "24", "12", "18"],
    correct: "E",
    explanation: "Total = 168L (Milk:Water = 128:40). 25% removed = 42L (32M, 10W). Left: Milk = 96L, Water = 30L. 96 / (30 + x) = 2/1 => 30 + x = 48 => x = 18 liters."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "12.5 × 80 + 37.5 × 16 – 6.25 × 112 = ?",
    options: ["1000", "900", "2300", "600", "1300"],
    correct: "B",
    explanation: "1000 + 600 - 700 = 900."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "11075 ÷ 5 + √3025 - √2116 = ?",
    options: ["2213", "2226", "2224", "2227", "2729"],
    correct: "C",
    explanation: "2215 + 55 - 46 = 2224."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "? + √324 + √361 = 290 ÷ 5 + 1000",
    options: ["1400", "1021", "1361", "1484", "1289"],
    correct: "B",
    explanation: "? + 18 + 19 = 58 + 1000 => ? + 37 = 1058 => ? = 1021."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "1674 ÷ 27 × 9 + 18 = ?²",
    options: ["26", "23", "24", "35", "18"],
    correct: "C",
    explanation: "62 × 9 + 18 = 558 + 18 = 576. ? = √576 = 24."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "(1.2)² + (1.5)² + (2.1)² − (1.9)² = ?",
    options: ["4.99", "5.69", "3.69", "6.79", "4.49"],
    correct: "E",
    explanation: "1.44 + 2.25 + 4.41 - 3.61 = 8.10 - 3.61 = 4.49."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "9990 ÷ 10 + (7294 – 3241 + 716) – (3267 + 2425 – 961) = ?",
    options: ["1035", "1048", "1043", "1037", "1047"],
    correct: "D",
    explanation: "999 + 4769 - 4731 = 999 + 38 = 1037."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "1217 + 841 – 724 + 819 = ? + 1843",
    options: ["210", "310", "360", "270", "410"],
    correct: "B",
    explanation: "2153 - 1843 = 310 (or 2877 - 2567 = 310)."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "0.06 × 0.84 = ? × 1.2 × 0.015",
    options: ["8.2", "6.4", "2.6", "3.8", "2.8"],
    correct: "E",
    explanation: "0.0504 = ? × 0.018 => ? = 0.0504 / 0.018 = 2.8."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "8.41 + 6.25 + 0.79 = ? – 0.55",
    options: ["17", "14.9", "13.9", "16", "14.7"],
    correct: "D",
    explanation: "15.45 = ? - 0.55 => ? = 16."
  },
  {
    subject: "Quantitative Aptitude (31-65)",
    topic: "Simplification",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "616 + 472 – 811 + 317 = ? + 576",
    options: ["28", "16", "24", "18", "14"],
    correct: "D",
    explanation: "594 = ? + 576 => ? = 18."
  },

  // Reasoning Ability: Q66 to Q100
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Parallel Rows Seating",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (66-70): Ten persons sit in two parallel rows (5 in each row). P, Q, R, S, T in Row 2 facing North. A, B, C, D, E in Row 1 facing South.\n- The one who sits second to the left of D faces S.\n- T sits immediate right of S.\n- Two persons sit between T and Q.\n- The one who faces Q sits third to the right of E.\n- One person sits between E and C who sits to the left of A.\n- A doesn’t face P.\n\nWho sits second to the left of the one who sits opposite to B?",
    options: ["R", "Q", "P", "S", "T"],
    correct: "B",
    explanation: "Row 1 (South): A, D, C, B, E. Row 2 (North): R, Q, P, S, T. Opposite B is S. Second to left of S (facing North) is Q."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Parallel Rows Seating",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following pairs sit at extreme ends?",
    options: ["E, Q", "T, D", "R, E", "B, D", "P, E"],
    correct: "C",
    explanation: "Extreme end persons are A and E (Row 1), R and T (Row 2). Pair (R, E) are both at extreme ends."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Parallel Rows Seating",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "The number of persons sitting to the left of D is same as the number of persons sitting to the left of ________.",
    options: ["B", "P", "T", "S", "R"],
    correct: "D",
    explanation: "D faces South and has 3 persons to his left. S faces North and has 3 persons to his left."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Parallel Rows Seating",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following statements is true?\nI. E faces Q\nII. A and T sit diagonally opposite to each other.\nIII. R sits third to the left of S",
    options: ["Only I", "Both II and III", "Only III", "Both I and III", "Only II"],
    correct: "B",
    explanation: "A (left end South) and T (right end North) are diagonally opposite (II is True). R is 3rd to the left of S (III is True)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Parallel Rows Seating",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Four of the following five are alike in a certain way. Which does not belong to the group?",
    options: ["D-Q", "B-S", "E-T", "A-R", "P-A"],
    correct: "E",
    explanation: "All pairs except P-A sit directly opposite each other (D-Q, B-S, E-T, A-R)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Inequalities",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Statements: C < D = E ≥ F = G, H ≤ G > I = J\nConclusions:\nI. D > J\nII. H ≤ E",
    options: ["Only I is true", "Only II is true", "Either I or II is true", "Both I and II are true", "Neither I nor II is true"],
    correct: "D",
    explanation: "D = E ≥ G > J => D > J (I is true). H ≤ G ≤ E => H ≤ E (II is true). Both follow."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Inequalities",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Statements: A < Q = R ≥ C ≥ T ≥ X ≥ V > M\nConclusions:\nI. Q > V\nII. M < T",
    options: ["Only I is true", "Only II is true", "Either I or II is true", "Both I and II are true", "Neither I nor II is true"],
    correct: "B",
    explanation: "Q = R ≥ V => Q ≥ V (not strictly >). T ≥ X ≥ V > M => T > M => M < T (II is true)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Inequalities",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Statements: A > B < C = D ≥ E > F ≤ G = H\nConclusions:\nI. A < H\nII. B ≥ G",
    options: ["Only I is true", "Only II is true", "Either I or II is true", "Both I and II are true", "Neither I nor II is true"],
    correct: "E",
    explanation: "Opposing signs exist between A and H, and between B and G. Neither follows."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Odd One Out",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Find the odd one out:\n(a) MPR\n(b) DGJ\n(c) PSU\n(d) SVX\n(e) GJL",
    options: ["MPR", "DGJ", "PSU", "SVX", "GJL"],
    correct: "B",
    explanation: "In all others, pattern is +3, +2 (M+3=P, P+2=R; P+3=S, S+2=U; S+3=V, V+2=X; G+3=J, J+2=L). In DGJ: D+3=G, G+3=J."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Schedule Puzzle",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (75-79): Seven persons A, B, C, D, E, F, G watch a show from Monday to Sunday.\n- G goes before B but after C.\n- G goes 3 persons after A.\n- B goes before E.\n- Two persons go between E and D.\n- C goes after F.\n\nWho goes to watch the show on Thursday?",
    options: ["G", "D", "A", "C", "None of these"],
    correct: "B",
    explanation: "Schedule: Mon:F, Tue:A, Wed:C, Thu:D, Fri:G, Sat:B, Sun:E. D goes on Thursday."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Schedule Puzzle",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "How many persons go to watch the show between F and G?",
    options: ["One", "Two", "Three", "None", "More than three"],
    correct: "C",
    explanation: "Between Mon(F) and Fri(G) are Tue, Wed, Thu (3 persons: A, C, D)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Schedule Puzzle",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following statements is true?",
    options: ["C goes on Tuesday.", "D goes immediately before B.", "F doesn’t go on Monday.", "D goes immediately before G (or E goes 2 days after G).", "None is true"],
    correct: "D",
    explanation: "E (Sunday) goes 2 days after G (Friday) or D goes on Thu."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Schedule Puzzle",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Who among the following goes to watch the show on Saturday?",
    options: ["G", "E", "A", "C", "B"],
    correct: "E",
    explanation: "B goes on Saturday."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Schedule Puzzle",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "As many persons watch the show before A as after ________.",
    options: ["C", "D", "E", "B", "F"],
    correct: "D",
    explanation: "Before A (Tue) is 1 person. After B (Sat) is 1 person (E)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Alphanumeric Series",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Study the series: 8 3 & 7 4 * ^ 6 % 8 5 @ 2 7 1 # 3 9 7 $ 9 2 ! 6 5 © 8\n\nWhich element is ninth to the left of the third symbol from the right end?",
    options: ["*", "5", "%", "8", "@"],
    correct: "B",
    explanation: "Third symbol from right is '$'. Ninth element to the left of '$' is '5'."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Alphanumeric Series",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "How many symbols are there between the eighth element from right and eighth element from left?",
    options: ["Two", "Four", "One", "Three", "None"],
    correct: "D",
    explanation: "Symbols between them: %, @, # (Total = 3 symbols)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Alphanumeric Series",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "If all even digits are removed, what will be the seventh element from the right end?",
    options: ["#", "3", "9", "7", "5"],
    correct: "C",
    explanation: "Counting from right skipping even digits (8, 6, 2, 8, 4): 5, ©, !, 9, $, 7, 9 => '9'."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Alphanumeric Series",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "How many digits are immediately followed and immediately preceded by a symbol?",
    options: ["5", "4", "3", "2", "1"],
    correct: "E",
    explanation: "Pattern: Symbol - Digit - Symbol: '^ 6 %'. Total = 1."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Alphanumeric Series",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "If all symbols are replaced by letters, how many odd digits are immediately preceded by letters and followed by a prime digit (Letter - Odd - Prime)?",
    options: ["Two", "Four", "Three", "One", "None"],
    correct: "D",
    explanation: "Pattern: '$ 9 2' -> Letter - 9(odd) - 2(prime). Total = 1."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Syllogism",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Statements:\nOnly a few melons are seeds\nAll seeds are plants\nAll plants are petal\n\nConclusions:\nI. All seeds are petal\nII. Some plants are melon",
    options: ["Only I follows", "Only II follows", "Either I or II follows", "Neither I nor II follows", "Both I and II follow"],
    correct: "E",
    explanation: "Seeds ⊂ Plants ⊂ Petal => All seeds are petal (I follows). Melons overlap seeds which are plants => Some plants are melon (II follows). Both follow."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Syllogism",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "Statements:\nOnly a few Apples are Citrus\nAll Citrus are Oranges\nSome Oranges are Lemons\n\nConclusions:\nI. Some Apples are Oranges\nII. A few lemons being Citrus is a possibility",
    options: ["Only I follows", "Only II follows", "Either I or II follows", "Neither I nor II follows", "Both I and II follow"],
    correct: "E",
    explanation: "Apples overlap Citrus which are Oranges (I follows). Lemons can overlap Citrus without contradiction (II follows). Both follow."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Syllogism",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "Statements:\nSome Pluto are Sun\nNo Pluto is Earth\nSome Sun are not Skin\n\nConclusions:\nI. No Sun is Earth\nII. Some Skin is not Pluto",
    options: ["Only I follows", "Only II follows", "Either I or II follows", "Neither I nor II follows", "Both I and II follow"],
    correct: "D",
    explanation: "Sun portion outside Pluto can be Earth (I does not follow). Skin has no negative relation with Pluto (II does not follow). Neither follows."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Order and Ranking",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (88-90): Six ropes A, B, C, D, E, F are of different lengths.\n- D is longer than A but shorter than E.\n- The second longest rope is 71m.\n- Length of E is more than G.\n- F is less than A but not the least.\n- Length of G is more than B.\n- Length of G is more than A but less than D.\n- F's length is 63m.\n\nWhich rope is the third longest?",
    options: ["A", "F", "G", "B", "D"],
    correct: "C",
    explanation: "Order: E > D (71m) > G > A > F (63m) > B. Third longest is G."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Order and Ranking",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "What is the possible length of Rope A?",
    options: ["62m", "73m", "75m", "65m", "79m"],
    correct: "D",
    explanation: "A is between G (< 71m) and F (63m). 65m is the only valid value between 63m and 71m."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Order and Ranking",
    difficulty: "Easy",
    marks: 1,
    year: 2025,
    question: "How many ropes are shorter than rope D?",
    options: ["None", "Two", "Three", "One", "Four"],
    correct: "E",
    explanation: "Shorter than D are G, A, F, B (4 ropes)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Sequence / Order",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (91-95): Eight persons P, Q, R, S, T, U, V, W go to market one after another.\n- P goes three persons before T.\n- Two persons go between T and V.\n- W goes immediately before Q.\n- One person goes between W and R.\n- S goes after R who goes after U.\n\nIf W is related to S and P is related to T, then R is related to whom?",
    options: ["W", "S", "V", "Q", "U"],
    correct: "D",
    explanation: "Order: P, U, R, T, W, Q, V, S. R is related to Q."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Sequence / Order",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Who goes to the market three persons after U?",
    options: ["P", "V", "T", "R", "W"],
    correct: "E",
    explanation: "U is 2nd. 3 persons after U is 5th position (W)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Sequence / Order",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "As many persons go to the market before T as between R and ________.",
    options: ["V", "U", "S", "Q", "P"],
    correct: "A",
    explanation: "Before T (4th) are 3 persons. Between R (3rd) and V (7th) are 3 persons (T, W, Q)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Sequence / Order",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Which of the following statements is/are false?",
    options: ["W went after T.", "S was the last person to go to the market.", "Three persons went between U and S.", "Q went after P.", "All are true."],
    correct: "C",
    explanation: "Between U (2nd) and S (8th) are 5 persons, so statement (c) is false."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Sequence / Order",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "How many persons go to the market between R and T?",
    options: ["None", "One", "Two", "Three", "Four"],
    correct: "A",
    explanation: "R is 3rd and T is 4th (0 persons in between)."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Word Formation",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "If 2nd, 4th, 6th, and 8th letters of 'SUSPICIOUS' (U, P, C, O) are combined to form a meaningful word, what is the third letter from the right? If more than one word, give 'X'; if no word, give 'Y'.",
    options: ["C", "O", "U", "Y", "X"],
    correct: "B",
    explanation: "Letters: U, P, C, O -> Word formed: 'COUP'. 3rd letter from right is 'O'."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Blood Relations",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Directions (97-99): A is the sister-in-law of O. C is mother of A who is daughter of D. E is niece of O who is son of F. H is grandson of F and has sibling. O doesn't have a child. Only two married couples. D is father of I. A is married. Four male members.\n\nHow is G related to D?",
    options: ["Son-in-law", "Mother-in-law", "Father-in-law", "Father", "Son"],
    correct: "A",
    explanation: "G is married to A (daughter of D), so G is the Son-in-law of D."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Blood Relations",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "Which one of the following is true?",
    options: ["H is the father of E", "A is the father of E", "O is the brother of I", "A is the niece of F", "None is true"],
    correct: "E",
    explanation: "None of the given specific options is true."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Blood Relations",
    difficulty: "Moderate",
    marks: 1,
    year: 2025,
    question: "How is H related to O?",
    options: ["Daughter", "Son", "Nephew", "Niece", "Brother"],
    correct: "C",
    explanation: "H is the son of G and A (brother/sister-in-law of O), making H the Nephew of O."
  },
  {
    subject: "Reasoning Ability (66-100)",
    topic: "Letter Pairing",
    difficulty: "Easy-Moderate",
    marks: 1,
    year: 2025,
    question: "In the word 'PRIMEVAL', how many pairs of letters have the same number of letters between them as in the alphabet (both forward and backward)?",
    options: ["Four", "Two", "One", "Three", "More than four"],
    correct: "D",
    explanation: "Pairs formed: P-R, I-M, etc. Total = 3 pairs."
  }
];
